"""Core browser management, authentication, and scraping utilities."""

from .auth import is_logged_in, wait_for_manual_login, warm_up_browser
from .browser import BrowserManager
from .exceptions import (
    AuthenticationError,
    ConcurrencyError,
    ElementNotFoundError,
    InteractionError,
    LinkedInScraperException,
    NetworkError,
    ProfileNotFoundError,
    QuotaExceededError,
    RateLimitError,
    ScrapingError,
    SelectorError,
)
from .interactions import (
    click_and_confirm,
    click_element,
    dismiss_modal,
    human_delay,
    type_text,
    upload_file,
    wait_for_modal,
)
from .pagination import (
    PaginatedResponse,
    build_paginated_response,
    decode_cursor,
    encode_next_cursor,
)
from .responses import ReadResult, WriteResult
from .schemas import JobCard, PersonCard, is_valid_job_card, is_valid_person_card
from .safety import (
    acquire_write_lock,
    audit_log,
    check_quota,
    check_session_health,
    execute_or_dry_run,
    get_captcha_count,
    get_session_health,
    is_session_degraded,
    record_security_challenge,
    record_successful_write,
    require_confirmation,
)
from .selectors import SELECTORS, AriaLabel, CSS, LocatorChain, Role, Text
from .utils import (
    backoff_with_jitter,
    detect_rate_limit,
    detect_rate_limit_post_action,
    handle_modal_close,
    scroll_to_bottom,
)

__all__ = [
    "AriaLabel",
    "AuthenticationError",
    "BrowserManager",
    "CSS",
    "ConcurrencyError",
    "JobCard",
    "LocatorChain",
    "ElementNotFoundError",
    "InteractionError",
    "LinkedInScraperException",
    "NetworkError",
    "PaginatedResponse",
    "PersonCard",
    "ProfileNotFoundError",
    "QuotaExceededError",
    "RateLimitError",
    "ReadResult",
    "Role",
    "SELECTORS",
    "ScrapingError",
    "SelectorError",
    "Text",
    "WriteResult",
    "acquire_write_lock",
    "audit_log",
    "backoff_with_jitter",
    "build_paginated_response",
    "check_quota",
    "check_session_health",
    "click_and_confirm",
    "click_element",
    "decode_cursor",
    "detect_rate_limit",
    "detect_rate_limit_post_action",
    "dismiss_modal",
    "encode_next_cursor",
    "execute_or_dry_run",
    "get_captcha_count",
    "get_session_health",
    "is_session_degraded",
    "handle_modal_close",
    "human_delay",
    "is_valid_job_card",
    "is_valid_person_card",
    "record_security_challenge",
    "record_successful_write",
    "require_confirmation",
    "is_logged_in",
    "scroll_to_bottom",
    "type_text",
    "upload_file",
    "wait_for_manual_login",
    "wait_for_modal",
    "warm_up_browser",
]
